Fix/Skip tests and add php 8.2 and 8.3.
beluga-php/docker-php pull request #66
Opened 2024-02-18 19:03 UTC by rodrigoaguilera

The red cross is annoying a gives the impression that the code is not useful at its current state.
What I did:
- Add php 8.2 and 8.3 testing. We can remove php 8.1 at the end of the year.
- Remove php 7 references in the CI
- Actually add phpstan and fixed a tiny warning to get it to level 2
- Fix some test that were referencing an old Jane-generated model for system events.
- Skipped the containerlogs test since it doesn't return the stream expected by the code. See https://github.com/beluga-php/docker-php/issues/19
- Skipped the websocket attach test since I don't think it works anymore. See https://github.com/xtermjs/xterm.js/issues/883

For this last one I tried for a while and what I get is a 101 http response with this headers
```
Upgrade: websocket                                                                                                                                               
Connection: Upgrade                                                   
Sec-WebSocket-Accept: Nq+SlyVfcOMLc9sY8KRmJVb3jBI=                                                                                                                            
```

Maybe we need a way to mark some endpoints as "Non-functional" (yet) or something similar.

For running the test locally I had to pull manually `busybox:latest`, the `imageCreate` endpoint won't pull it automatically. I'm not sure if this will fail in the CI.

2024-02-18 19:24 UTC, rodrigoaguilera commented
And its green :) :green_circle:

2024-02-19 12:12 UTC, flavioheleno requested changes

2024-02-19 12:12 UTC, flavioheleno commented on src/Context/ContextBuilder.php
> +     * @param $fs \Symfony\Component\Filesystem\Filesystem
```suggestion
     * @param \Symfony\Component\Filesystem\Filesystem $fs
```

2024-02-19 12:12 UTC, flavioheleno commented on src/Docker.php
> +    ) : self
```suggestion
    ): self
```

2024-02-19 13:04 UTC, flavioheleno approved these changes

2024-02-19 13:04 UTC, merged